<?php
require_once __DIR__ . '/inc/header.php'; require_login(); require_role(array('admin','organizer','viewer'));
$canEdit=in_array($_SESSION['role'],array('admin','organizer'),true);
if($canEdit && $_SERVER['REQUEST_METHOD']==='POST'){ $id=(int)($_POST['dog_id']??0);$owner=(int)($_POST['owner_id']??0);$name=trim($_POST['name']??'');$breed=trim($_POST['breed']??'');$sex=trim($_POST['sex']??'R');$country=trim($_POST['country_code']??'AT');
if($id>0){$st=$mysqli->prepare('UPDATE dogs SET owner_id=?,name=?,breed=?,sex=?,country_code=? WHERE dog_id=?');$st->bind_param('issssi',$owner,$name,$breed,$sex,$country,$id);} else {$st=$mysqli->prepare('INSERT INTO dogs (owner_id,name,breed,sex,country_code) VALUES (?,?,?,?,?)');$st->bind_param('issss',$owner,$name,$breed,$sex,$country);} $st->execute();$st->close();}
$q=trim($_GET['q']??'');$page=get_page();$off=get_offset($page,PAGE_SIZE);$like='%'.$q.'%';
$owners=array();$s1=$mysqli->prepare('SELECT owner_id,name FROM owners ORDER BY name LIMIT 500');$s1->execute();$s1->bind_result($ooid,$oon);while($s1->fetch()){$owners[$ooid]=$oon;}$s1->close();
$st=$mysqli->prepare('SELECT d.dog_id,d.owner_id,d.name,d.breed,d.sex,d.country_code FROM dogs d WHERE (?="" OR d.name LIKE ? OR d.breed LIKE ?) ORDER BY d.dog_id DESC LIMIT ? OFFSET ?');$st->bind_param('sssii',$q,$like,$like,$ps=PAGE_SIZE,$off);$st->execute();$st->bind_result($id,$owner,$name,$breed,$sex,$country);
?>
<?php if($canEdit): ?><div class="card"><form method="post" class="row"><input type="hidden" name="dog_id" value="0"><div class="col"><label>Owner<select name="owner_id"><?php foreach($owners as $k=>$v): ?><option value="<?php echo (int)$k; ?>"><?php echo e($v); ?></option><?php endforeach; ?></select></label></div><div class="col"><label>Name<input name="name" required></label></div><div class="col"><label>Breed<input name="breed" required></label></div><div class="col"><label>Sex<select name="sex"><option>R</option><option>H</option></select></label></div><div class="col"><label>Country<input name="country_code" value="AT"></label></div><div class="col"><button><?php echo e(t('save')); ?></button></div></form></div><?php endif; ?>
<table><tr><th>ID</th><th>Name</th><th>Breed</th><th>Sex</th><th>Owner</th></tr><?php while($st->fetch()): ?><tr><td><?php echo (int)$id; ?></td><td><?php echo e($name); ?></td><td><?php echo e($breed); ?></td><td><?php echo e($sex); ?></td><td><?php echo e(isset($owners[$owner])?$owners[$owner]:''); ?></td></tr><?php endwhile; ?></table>
<?php $st->close(); require_once __DIR__ . '/inc/footer.php'; ?>
