<?php
require_once __DIR__ . '/inc/header.php'; require_login(); require_role(array('admin','organizer','viewer'));
$canEdit=in_array($_SESSION['role'],array('admin','organizer'),true);$warn='';
if($canEdit && $_SERVER['REQUEST_METHOD']==='POST'){
$id=(int)($_POST['event_id']??0);$type=$_POST['type_code']??'TRACK';$date=$_POST['event_date']??date('Y-m-d');$loc=trim($_POST['location']??'');$cc=trim($_POST['country_code']??'AT');$el=$_POST['event_lang']??'de';$title=trim($_POST['title_main']??'');$small=trim($_POST['title_en_small']??'');$temp=$_POST['temperature_c']!==''?(float)$_POST['temperature_c']:null;$limit=(float)($_POST['temp_limit_c']??25);
$judge=(int)($_POST['judge_count']??3);$max=(int)($_POST['max_per_heat']??6);$offi=trim($_POST['officials']??'');$notes=trim($_POST['notes_long']??'');$spon=trim($_POST['sponsors_text']??'');
if($temp!==null && $temp>$limit){$warn='Temperature exceeds limit';}
if($id>0){$st=$mysqli->prepare('UPDATE events SET type_code=?,event_date=?,location=?,country_code=?,event_lang=?,title_main=?,title_en_small=?,temperature_c=?,temp_limit_c=?,judge_count=?,max_per_heat=?,officials=?,notes_long=?,sponsors_text=? WHERE event_id=?');$st->bind_param('sssssssddiisssi',$type,$date,$loc,$cc,$el,$title,$small,$temp,$limit,$judge,$max,$offi,$notes,$spon,$id);} else {$st=$mysqli->prepare('INSERT INTO events (type_code,event_date,location,country_code,event_lang,title_main,title_en_small,temperature_c,temp_limit_c,judge_count,max_per_heat,officials,notes_long,sponsors_text) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$st->bind_param('sssssssddiisss',$type,$date,$loc,$cc,$el,$title,$small,$temp,$limit,$judge,$max,$offi,$notes,$spon);} $st->execute();$st->close();
}
$st=$mysqli->prepare('SELECT event_id,type_code,event_date,location,event_lang,title_main,temperature_c,temp_limit_c,max_per_heat FROM events ORDER BY event_date DESC LIMIT 100');$st->execute();$st->bind_result($id,$type,$date,$loc,$el,$title,$temp,$limit,$max);
?>
<div class="card"><form method="post" class="row"><input type="hidden" name="event_id" value="0"><div class="col"><label>Type<select name="type_code"><option>TRACK</option><option>COURSING</option><option>FUNRUN</option></select></label></div><div class="col"><label>Date<input type="date" name="event_date" value="<?php echo date('Y-m-d'); ?>"></label></div><div class="col"><label>Location<input name="location" required></label></div><div class="col"><label>Lang<select name="event_lang"><option>de</option><option>en</option><option>hu</option><option>cs</option><option>sk</option></select></label></div><div class="col"><label>Title<input name="title_main" required></label></div><div class="col"><label>Temp<input name="temperature_c"></label></div><div class="col"><label>Temp limit<input name="temp_limit_c" value="25"></label></div><div class="col"><label>max/heat<input name="max_per_heat" value="6"></label></div><div class="col"><button><?php echo e(t('save')); ?></button></div></form><?php if($warn):?><p><?php echo e($warn); ?></p><?php endif;?></div>
<table><tr><th>ID</th><th>Date</th><th>Type</th><th>Title</th><th>Location</th></tr><?php while($st->fetch()): ?><tr><td><?php echo (int)$id;?></td><td><?php echo e($date);?></td><td><?php echo e($type);?></td><td><?php echo e($title);?></td><td><?php echo e($loc);?></td></tr><?php endwhile; ?></table>
<?php $st->close(); require_once __DIR__ . '/inc/footer.php'; ?>
