<?php
require_once __DIR__ . '/inc/header.php'; require_login(); require_role(array('admin','organizer','viewer'));
$canEdit=in_array($_SESSION['role'],array('admin','organizer'),true);
$eventId=(int)($_GET['event_id']??0);
if($canEdit && $_SERVER['REQUEST_METHOD']==='POST'){
$action=$_POST['action']??'';
if($action==='create_heat'){$event=(int)$_POST['event_id'];$no=(int)$_POST['heat_no'];$ht=$_POST['heat_type'];$class=trim($_POST['class_code']);$group=$_POST['group_code'];$dist=(int)$_POST['distance_m'];$title=trim($_POST['title_cached']);$st=$mysqli->prepare('INSERT INTO heats (event_id,heat_no,heat_type,class_code,group_code,distance_m,title_cached) VALUES (?,?,?,?,?,?,?)');$st->bind_param('iisssis',$event,$no,$ht,$class,$group,$dist,$title);$st->execute();$st->close();$eventId=$event;}
if($action==='assign'){$event=(int)$_POST['event_id'];$heat=(int)$_POST['heat_id'];$entry=(int)$_POST['entry_id'];$stc=$mysqli->prepare('SELECT e.max_per_heat, (SELECT COUNT(*) FROM heat_assignments WHERE heat_id=?) FROM events e JOIN heats h ON h.event_id=e.event_id WHERE h.heat_id=? LIMIT 1');$stc->bind_param('ii',$heat,$heat);$stc->execute();$stc->bind_result($max,$cnt);$ok=$stc->fetch();$stc->close();if($ok && $cnt<$max){$st=$mysqli->prepare('INSERT IGNORE INTO heat_assignments (event_id,heat_id,entry_id) VALUES (?,?,?)');$st->bind_param('iii',$event,$heat,$entry);$st->execute();$st->close();}$eventId=$event;}
if($action==='auto_startno'){$heat=(int)$_POST['heat_id'];$st=$mysqli->prepare('SELECT ha_id FROM heat_assignments WHERE heat_id=? AND (start_no IS NULL OR start_no=0) ORDER BY ha_id');$st->bind_param('i',$heat);$st->execute();$st->bind_result($ha);$n=1;while($st->fetch()){$u=$mysqli->prepare('UPDATE heat_assignments SET start_no=? WHERE ha_id=?');$u->bind_param('ii',$n,$ha);$u->execute();$u->close();$n++;}$st->close();}
}
$events=array();$s1=$mysqli->prepare('SELECT event_id,title_main FROM events ORDER BY event_date DESC LIMIT 200');$s1->execute();$s1->bind_result($eid,$et);while($s1->fetch()){$events[$eid]=$et;}$s1->close();
$heats=array(); if($eventId>0){$s2=$mysqli->prepare('SELECT heat_id,heat_no,title_cached FROM heats WHERE event_id=? ORDER BY heat_no');$s2->bind_param('i',$eventId);$s2->execute();$s2->bind_result($hid,$hno,$htit);while($s2->fetch()){$heats[$hid]=$hno.' - '.$htit;}$s2->close();}
$entries=array();if($eventId>0){$s3=$mysqli->prepare('SELECT entry_id,class_code FROM entries WHERE event_id=? ORDER BY entry_id');$s3->bind_param('i',$eventId);$s3->execute();$s3->bind_result($enid,$cc);while($s3->fetch()){$entries[$enid]='#'.$enid.' '.$cc;}$s3->close();}
?>
<div class="card"><form method="get"><label>Event<select name="event_id" onchange="this.form.submit()"><option value="0">--</option><?php foreach($events as $k=>$v):?><option value="<?php echo(int)$k;?>" <?php if($eventId===$k)echo'selected';?>><?php echo e($v);?></option><?php endforeach;?></select></label></form></div>
<?php if($canEdit && $eventId>0): ?><div class="card"><form method="post" class="row"><input type="hidden" name="action" value="create_heat"><input type="hidden" name="event_id" value="<?php echo(int)$eventId;?>"><div class="col"><label>No<input name="heat_no" required></label></div><div class="col"><label>Type<select name="heat_type"><option>HEAT1</option><option>HEAT2</option><option>FINAL_A</option><option>FINAL_B</option><option>FINAL_C</option><option>COURSING_RUN1</option><option>COURSING_RUN2</option><option>FUNRUN</option></select></label></div><div class="col"><label>Class<input name="class_code" required></label></div><div class="col"><label>Group<select name="group_code"><option>FIELD</option><option>SOLO</option></select></label></div><div class="col"><label>Distance<input name="distance_m" value="350"></label></div><div class="col"><label>Title<input name="title_cached" required></label></div><div class="col"><button>Create Heat</button></div></form></div>
<div class="card"><form method="post" class="row"><input type="hidden" name="action" value="assign"><input type="hidden" name="event_id" value="<?php echo(int)$eventId;?>"><div class="col"><label>Heat<select name="heat_id"><?php foreach($heats as $k=>$v):?><option value="<?php echo(int)$k;?>"><?php echo e($v);?></option><?php endforeach;?></select></label></div><div class="col"><label>Entry<select name="entry_id"><?php foreach($entries as $k=>$v):?><option value="<?php echo(int)$k;?>"><?php echo e($v);?></option><?php endforeach;?></select></label></div><div class="col"><button>Assign</button></div></form></div><?php endif; ?>
<?php require_once __DIR__ . '/inc/footer.php'; ?>
