<?php
require_once __DIR__ . '/inc/header.php'; require_login();
$eventId=(int)($_GET['event_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
$eventId=(int)$_POST['event_id'];$cfg=array('cover'=>!empty($_POST['cover']),'officials'=>!empty($_POST['officials']),'startlists'=>!empty($_POST['startlists']),'results'=>!empty($_POST['results']),'rules'=>!empty($_POST['rules']),'sponsors'=>!empty($_POST['sponsors']));
if(!empty($_POST['save_snapshot'])){$json=json_encode($cfg);$html='<h1>Catalog Snapshot</h1><pre>'.e($json).'</pre>';$chk=$mysqli->prepare('SELECT COUNT(*) FROM catalog_snapshots WHERE event_id=?');$chk->bind_param('i',$eventId);$chk->execute();$chk->bind_result($c);$chk->fetch();$chk->close();$isOrig=$c==0?1:0;$ver=null;if(!$isOrig){$mx=$mysqli->prepare('SELECT IFNULL(MAX(version_no),1) FROM catalog_snapshots WHERE event_id=?');$mx->bind_param('i',$eventId);$mx->execute();$mx->bind_result($m);$mx->fetch();$mx->close();$ver=$m+1;} $cr=(int)$_SESSION['user_id'];$ins=$mysqli->prepare('INSERT INTO catalog_snapshots (event_id,created_by,is_original,version_no,config_json,html_cache) VALUES (?,?,?,?,?,?)');$ins->bind_param('iiiiss',$eventId,$cr,$isOrig,$ver,$json,$html);$ins->execute();$ins->close();}
header('Location: katalog_pdf.php?event_id='.$eventId.'&cover='.(int)$cfg['cover'].'&officials='.(int)$cfg['officials'].'&startlists='.(int)$cfg['startlists'].'&results='.(int)$cfg['results'].'&rules='.(int)$cfg['rules'].'&sponsors='.(int)$cfg['sponsors']);exit;
}
$events=array();$st=$mysqli->prepare('SELECT event_id,title_main FROM events ORDER BY event_date DESC LIMIT 200');$st->execute();$st->bind_result($eid,$title);while($st->fetch()){$events[$eid]=$title;} $st->close();
?><div class="card"><form method="post"><label>Event<select name="event_id"><?php foreach($events as $k=>$v):?><option value="<?php echo(int)$k;?>" <?php if($eventId===$k)echo'selected';?>><?php echo e($v);?></option><?php endforeach;?></select></label><label><input type="checkbox" name="cover" checked>Deckblatt</label><label><input type="checkbox" name="officials" checked>Officials</label><label><input type="checkbox" name="startlists" checked>Startlisten</label><label><input type="checkbox" name="results" checked>Ergebnisse</label><label><input type="checkbox" name="rules" checked>Regeln</label><label><input type="checkbox" name="sponsors" checked>Sponsoren</label><label><input type="checkbox" name="save_snapshot">Snapshot speichern</label><button>PDF erstellen</button></form></div><?php require_once __DIR__ . '/inc/footer.php'; ?>
