<?php
require_once __DIR__ . '/inc/header.php'; require_login(); require_role(array('admin','organizer','viewer'));
$canEdit=in_array($_SESSION['role'],array('admin','organizer'),true);
$eventId=(int)($_GET['event_id']??($_POST['event_id']??0));
if($canEdit && $_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['entry_id'])){
$event=(int)$_POST['event_id'];$heat=(int)$_POST['heat_id'];$entry=(int)$_POST['entry_id'];$status=$_POST['status']??'OK';$dq=trim($_POST['dq_reason']??'');$timeMs=parse_time_to_ms($_POST['time_txt']??'');
$s=(int)($_POST['s_points']??0);$a=(int)($_POST['a_points']??0);$ept=(int)($_POST['e_points']??0);$f=(int)($_POST['f_points']??0);$h=(int)($_POST['h_points']??0);$tot=$s+$a+$ept+$f+$h;
$chk=$mysqli->prepare('SELECT perf_id FROM performance WHERE heat_id=? AND entry_id=? LIMIT 1');$chk->bind_param('ii',$heat,$entry);$chk->execute();$chk->bind_result($pid);
if($chk->fetch()){$chk->close();$u=$mysqli->prepare('UPDATE performance SET time_ms=?,s_points=?,a_points=?,e_points=?,f_points=?,h_points=?,total_points=?,status=?,dq_reason=? WHERE perf_id=?');$u->bind_param('iiiiiiissi',$timeMs,$s,$a,$ept,$f,$h,$tot,$status,$dq,$pid);$u->execute();$u->close();}
else{$chk->close();$i=$mysqli->prepare('INSERT INTO performance (event_id,heat_id,entry_id,time_ms,s_points,a_points,e_points,f_points,h_points,total_points,status,dq_reason) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)');$i->bind_param('iiiiiiiiiiss',$event,$heat,$entry,$timeMs,$s,$a,$ept,$f,$h,$tot,$status,$dq);$i->execute();$i->close();}
$eventId=$event;
}
$events=array();$s1=$mysqli->prepare('SELECT event_id,title_main,type_code FROM events ORDER BY event_date DESC LIMIT 200');$s1->execute();$s1->bind_result($eid,$et,$etype);$eventType='TRACK';while($s1->fetch()){$events[$eid]=array($et,$etype);if($eid===$eventId){$eventType=$etype;}}$s1->close();
$rows=array();if($eventId>0){$st=$mysqli->prepare('SELECT h.heat_id,h.title_cached,ha.entry_id,p.time_ms,p.s_points,p.a_points,p.e_points,p.f_points,p.h_points,p.total_points,p.status,p.dq_reason FROM heats h JOIN heat_assignments ha ON ha.heat_id=h.heat_id LEFT JOIN performance p ON p.heat_id=h.heat_id AND p.entry_id=ha.entry_id WHERE h.event_id=? ORDER BY h.heat_no,ha.start_no,ha.ha_id');$st->bind_param('i',$eventId);$st->execute();$st->bind_result($hid,$htitle,$entry,$tm,$sp,$ap,$ep,$fp,$hp,$tp,$stt,$dq);while($st->fetch()){$rows[]=array($hid,$htitle,$entry,$tm,$sp,$ap,$ep,$fp,$hp,$tp,$stt,$dq);} $st->close();}
?>
<div class="card"><form method="get"><label>Event<select name="event_id" onchange="this.form.submit()"><option value="0">--</option><?php foreach($events as $k=>$v):?><option value="<?php echo(int)$k;?>" <?php if($eventId===$k)echo'selected';?>><?php echo e($v[0]);?></option><?php endforeach;?></select></label></form></div>
<?php foreach($rows as $r): ?><div class="card"><form method="post" class="row"><input type="hidden" name="event_id" value="<?php echo(int)$eventId;?>"><input type="hidden" name="heat_id" value="<?php echo(int)$r[0];?>"><input type="hidden" name="entry_id" value="<?php echo(int)$r[2];?>"><div class="col"><strong><?php echo e($r[1]);?> / Entry <?php echo(int)$r[2];?></strong></div><?php if($eventType==='COURSING'): ?><div class="col"><input name="s_points" value="<?php echo e((string)$r[4]);?>" placeholder="S"></div><div class="col"><input name="a_points" value="<?php echo e((string)$r[5]);?>" placeholder="A"></div><div class="col"><input name="e_points" value="<?php echo e((string)$r[6]);?>" placeholder="E"></div><div class="col"><input name="f_points" value="<?php echo e((string)$r[7]);?>" placeholder="F"></div><div class="col"><input name="h_points" value="<?php echo e((string)$r[8]);?>" placeholder="H"></div><?php else: ?><div class="col"><input name="time_txt" value="<?php echo e(ms_to_time($r[3]));?>" placeholder="mm:ss.mmm"></div><?php endif; ?><div class="col"><select name="status"><option>OK</option><option>NS</option><option>NA</option><option>DIS</option><option>V</option><option>DQ</option></select></div><div class="col"><input name="dq_reason" value="<?php echo e((string)$r[11]);?>" placeholder="DQ reason"></div><div class="col"><button>Save</button></div></form></div><?php endforeach; ?>
<?php require_once __DIR__ . '/inc/footer.php'; ?>
